from LocalSearchAlgorithms.ants.core import AntAlgorithm
from LocalSearchAlgorithms.ants.main import AntFlowShop
from LocalSearchAlgorithms.ants.TravelingSalesman import AntTravelingSalesman
from LocalSearchAlgorithms.ants.favarange import AntFAvarange